### DISCUSSION TITLE
Not able to see ed25519 support in ostree feature list

### DISCUSSION THREAD

**Discussion by bhaijiyunus** [ostreedev/ostree#3254] [Q&A]
Hi,

1. I created the Ubuntu-24.04 docker with ostree-24.5 support but I don't see `sign-ed25519` & `OpenSSL` support in the `ostree --version`.

```
root@1843858f4e27:/home/ost-sign# ostree --version
libostree:
 Version: '2024.5'
 Features:
  - inode64
  - initial-var
  - libcurl
  - libsoup3
  - gpgme
  - composefs
  - ex-fsverity
  - libarchive
  - selinux
  - avahi
  - libmount
  - systemd
  - release
  - p2p
root@1843858f4e27:/home/ost-sign# 
```

2.  I cloned the latest ostree source code from github & build it on ubuntu-22.04 VM but there also I don't see the `sign-ed25519` & `OpenSSL` support. 
```
jbhaijy@jbhaijy:~/ost-client$ ostree --version
libostree:
 Version: '2024.6'
 Git: v2024.5-22-gc8c436e5db920b95bfd1bea5b42800da3ae819dd
 DevelBuild: yes
 Features:
  - inode64
  - initial-var
  - gpgme
  - ex-fsverity
  - selinux
  - libmount
  - devel
  - p2p
jbhaijy@jbhaijy:~/ost-client$ 
```
3. How we can enable `sign-ed25519` & `OpenSSL`  support in ostree?
4. I want to sign the ostree commit with ed25519 keypair. Please let know what are the required dependencies to sign the commits with ed25519 key?

Regards,
jbhaijy
