### ISSUE TITLE
ostree init stuck on docker volume

### ISSUE THREAD

**Issue by itsManjeet** [ostreedev/ostree#3064]
When I run the command `ostree init --repo=/src/repo` inside a Docker container with the `-v /src:/src` volume mapping, it seems to get stuck for hours without any output, even when you use the `--verbose` flag. The container is privileged and that you have Fuse set up.The same command works fine when executed outside of a Docker shared volume.

Host System: Ubuntu 22.04.3 LTS (VPS)

```
ostree --version
libostree:
 Version: '2023.2'
 Features:
  - libcurl
  - gpgme
  - ex-fsverity
  - libarchive
  - openssl
  - avahi
  - libmount
  - systemd
  - release
  - p2p
```

strace log https://gist.github.com/itsManjeet/d982b8f4ebb43d95a1cb332d0e4f4d18
